title: Maxime's Personal Blog
description: Join Maxime Delobel on a journey from neuroscience to cybersecurity. This blog documents my learning process, sharing beginner-friendly insights and notes to make the world of cybersecurity more approachable for newcomers like me.
show_downloads: true
baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://maxime-delobel.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Maxime Delobel
image: /thumbnail-jumbo.png

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['Posts', 'About', 'Contact']
